ALTER TABLE leads ADD COLUMN IF NOT EXISTS has_3d_scan BOOLEAN DEFAULT false;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS scan_type TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS scan_file_name TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS scan_file_mime TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS scan_file_data TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS scan_url TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS payment_preference TEXT DEFAULT 'unknown';
ALTER TABLE leads ADD COLUMN IF NOT EXISTS credit_months INTEGER;

ALTER TABLE patients ADD COLUMN IF NOT EXISTS payment_preference TEXT DEFAULT 'unknown';
ALTER TABLE patients ADD COLUMN IF NOT EXISTS credit_months INTEGER;
ALTER TABLE patients ADD COLUMN IF NOT EXISTS has_3d_scan BOOLEAN DEFAULT false;
ALTER TABLE patients ADD COLUMN IF NOT EXISTS scan_type TEXT;
ALTER TABLE patients ADD COLUMN IF NOT EXISTS scan_file_name TEXT;
ALTER TABLE patients ADD COLUMN IF NOT EXISTS scan_file_mime TEXT;
ALTER TABLE patients ADD COLUMN IF NOT EXISTS scan_file_data TEXT;
ALTER TABLE patients ADD COLUMN IF NOT EXISTS scan_url TEXT;

ALTER TABLE appointments ADD COLUMN IF NOT EXISTS payment_preference TEXT;
